### ISSUE TITLE
[dataModelUpdate]: assay_proteomics

### ISSUE THREAD

**Issue by ameliakallaher** [eliteportal/data-models#20]
### Change Type

Update

### Template to add or update

assay_proteomics

### RFC Link

https://docs.google.com/spreadsheets/d/1r-XsL6x5_7cAAQ-Bf-7-buCtMAuTBx2fFT8CQIWRGk0/edit?usp=sharing

### Additional Comments

As discussed in the meeting with Beth Wilmot on 9/1, I updated the proteomics RFC spreadsheet to ensure the current proteomics template has adequate information to accommodate the metadata produced by key proteomics platforms used by EL researchers (ex., SomaScan, OLink, and Seer). I also updated the valid values list to accommodate DCA configurations (ex., removed "other" and expansive valid values not needed for assay level metadata). All keys/attributes/metadata terms are listed as required. For DCA, a data contributor should be able to write in a value OR provide one of these values:
Unknown, Not collected, Not applicable, Not specified.

**Comment by nlee-sage** [comment]
The updated Proteomics RFC has been added to the data model.
