### ISSUE TITLE
[dataModelUpdate]: metabolomics

### ISSUE THREAD

**Issue by ameliakallaher** [eliteportal/data-models#22]
### Change Type

Update

### Template to add or update

assay_metabolomics

### RFC Link

https://docs.google.com/spreadsheets/d/1yQpQVnMLG4qlBBivTrya8NAF8oFJ17MTl55u_Y9_UXc/edit#gid=0

### Additional Comments

I updated the metabolomics RFC primarily for metabolomics data generated by LC and LLFS. ILO planned to produce metabolomics data but currently needs dedicated funding for it. Similar to proteomics, extensive valid value lists were removed, and "other" as an option was also removed. Units of measure valid value lists were kept as they are not required keys. This update will be used for both human and non-human studies.

**Comment by nlee-sage** [comment]
Metabolomics template has been integrated into the data model and is downloadable in DCA.
