### ISSUE TITLE
[dataModelUpdate]: genotyping_human_assay

### ISSUE THREAD

**Issue by ameliakallaher** [eliteportal/data-models#27]
### Change Type

Update

### Template to add or update

genotyping_human_assay

### RFC Link

https://docs.google.com/spreadsheets/d/1UqlfwepC-7Zc73g2UPm2zQh_O9FEKKOsBVWmKOQ6wzE/edit?usp=sharing

### Additional Comments

I updated the genotyping assay to designate this template is for human data, as well as added additional new attributes to the RFC spreadsheet and fixed any typos, variable names, valid value lists, and TRUE/FALSE for required or not required attributes.

**Comment by nlee-sage** [comment]
genotyping assay now available in DCA. I tested downloading the manifest on LLFS folder and it worked.

**Comment by ameliakallaher** [comment]
I made one update: removed the valid values for the sample type key, not sure if you already made that update.
