### ISSUE TITLE
[dataModelUpdate]: bsSeq

### ISSUE THREAD

**Issue by ameliakallaher** [eliteportal/data-models#28]
### Change Type

Update

### Template to add or update

assay_bsSeq

### RFC Link

https://docs.google.com/spreadsheets/d/1SbYZ8-BeHqC9Xx0yipYGILKXLDdNwo1EADqup-yMPxQ/edit?usp=sharing

### Additional Comments

Updated attributes and valid value lists for LLFS data upload and to comply with new data model rules (no longer need "specify" attributes, no longer provide valid value lists for attributes like sample type, measurement technique, technology platform version, etc.). As well as removed some duplicate attributes.

**Comment by nlee-sage** [comment]
bsSeq template now available in DCA
